language: minimal

env:
  - LUA=lua5.1

addons:
  apt:
    packages:
      - luajit
      - luarocks

install:
  - luarocks install --local --verbose luacheck
  - luarocks install --local --verbose luafilesystem
  - luarocks install --local --verbose busted
  - luarocks install --local --verbose xml2lua
  - luarocks install --local --verbose penlight
  - luarocks install --local --verbose bit32
  - luarocks install --local --verbose bitlib

before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -q
  - eval `luarocks --lua-version=5.1 path`
  - /home/travis/.luarocks/bin/busted --lua=lua5.1 .
  - sudo apt-get update
  - sudo apt-get -y install jq

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash  -s -- -g "1.13.4"

notifications:
  email:
    on_success: never
    on_failure: always